language: python
python:
  - "3.6"

# command to install dependencies
install:
  - make install_deps

# command to run tests
script:
  - pip install -r requirements.txt
  - python -m pytest cutevariant tests -vv
